site_name: mbed Handbook

docs_dir: docs

pages:
- ['index.md','Introduction to the mbed handbook']
- ['Introduction/Code_Base.md','Introduction','mbed OS code base']
- ['Build_Tools/Intro.md', 'Build Tools' ,'Introduction to the build tools']
- ['Build_Tools/mbed_CLI/mbed_CLI.md', 'Build Tools' ,'mbed CLI']
