site_name: mbed OS 16.07

docs_dir: docs

pages:
- ['index.md','Introduction to mbed OS 16.07']
- ['getting_started/what_need.md', 'Getting started', 'What you need']
- ['getting_started/first_program.md', 'Getting started', 'First program']
- ['APIs/intro.md', 'Getting started', 'Writing applications with the mbed OS APIs']
- ['APIs/io/inputs_outputs.md', 'Input and output APIs', 'Handling inputs and outputs']
- ['APIs/io/AnalogIn.md', 'Input and output APIs', 'AnalogIn']
- ['APIs/io/AnalogOut.md', 'Input and output APIs', 'AnalogOut']
- ['APIs/io/DigitalIn.md', 'Input and output APIs', 'DigitalIn']
- ['APIs/io/DigitalOut.md', 'Input and output APIs', 'DigitalOut']
- ['APIs/io/DigitalInOut.md', 'Input and output APIs', 'DigitalInOut']
- ['APIs/io/BusIn.md', 'Input and output APIs', 'BusIn']
- ['APIs/io/BusOut.md', 'Input and output APIs', 'BusOut']
- ['APIs/io/BusInOut.md', 'Input and output APIs', 'BusInOut']
- ['APIs/io/PortIn.md', 'Input and output APIs', 'PortIn']
- ['APIs/io/PortOut.md', 'Input and output APIs', 'PortOut']
- ['APIs/io/PortInOut.md', 'Input and output APIs', 'PortInOut']
- ['APIs/io/PwmOut.md', 'Input and output APIs', 'PwmOut']
- ['APIs/io/InterruptIn.md', 'Input and output APIs', 'InterruptIn']
- ['APIs/interfaces/interfaces.md', 'Interface APIs', 'Interface options']
- ['APIs/interfaces/digital/Serial.md', 'Interface APIs', 'Serial']
- ['APIs/interfaces/digital/SPI.md', 'Interface APIs', 'SPI']
- ['APIs/interfaces/digital/SPISlave.md', 'Interface APIs', 'SPISlave']
- ['APIs/interfaces/digital/I2C.md', 'Interface APIs', 'I2C']
- ['APIs/interfaces/digital/I2CSlave.md', 'Interface APIs', 'I2CSlave']
- ['APIs/interfaces/digital/CAN.md', 'Interface APIs', 'CAN']
- ['APIs/interfaces/USBDevice/USBMouse.md', 'Interface APIs', 'USBMouse']
- ['APIs/interfaces/USBDevice/USBKeyboard.md', 'Interface APIs', 'USBKeyboard']
- ['APIs/interfaces/USBDevice/USBMouseKeyboard.md', 'Interface APIs', 'USBMouseKeyboard']
- ['APIs/interfaces/USBDevice/USBHID.md', 'Interface APIs', 'USBHID']
- ['APIs/interfaces/USBDevice/USBMIDI.md', 'Interface APIs', 'USBMIDI']
- ['APIs/interfaces/USBDevice/USBSerial.md', 'Interface APIs', 'USBSerial']
- ['APIs/interfaces/USBDevice/USBAudio.md', 'Interface APIs', 'USBAudio']
- ['APIs/interfaces/USBDevice/USBMSD.md', 'Interface APIs', 'USBMSD']
- ['APIs/interfaces/USBHost/USBHostMouse.md', 'Interface APIs', 'USBHostMouse']
- ['APIs/interfaces/USBHost/USBHostKeyboard.md', 'Interface APIs', 'USBHostKeyboard']
- ['APIs/interfaces/USBHost/USBHostMSD.md', 'Interface APIs', 'USBHostMSD']
- ['APIs/interfaces/USBHost/USBHostSerial.md', 'Interface APIs', 'USBHostSerial']
- ['APIs/interfaces/USBHost/USBHostHub.md', 'Interface APIs', 'USBHostHub']
- ['APIs/communication/communication.md', 'Communication APIs', 'Communication options']
- ['APIs/communication/network_stack.md', 'Communication APIs', 'Network stack']
- ['APIs/communication/ble.md', 'Communication APIs', 'BLE']
- ['APIs/communication/ethernet.md', 'Communication APIs', 'Ethernet']
- ['APIs/communication/wifi.md', 'Communication APIs', 'WiFi']
- ['APIs/communication/radio.md', 'Communication APIs', 'Radio']
- ['APIs/security/security.md', 'Security APIs', 'Securing devices and connections']
- ['APIs/security/uvisor.md', 'Security APIs', 'mbed uVisor']
- ['APIs/security/tls.md', 'Security APIs', 'mbed TLS']
- ['APIs/tasks/tasks.md', 'Task management APIs', 'Managing tasks']
- ['APIs/tasks/timers.md', 'Task management APIs', 'Timers']
- ['APIs/tasks/rtos.md', 'Task management APIs', 'RTOS']
- ['APIs/memory_files/memory_files.md', 'Memory and file system APIs', 'Managing the memory and file system']
- ['APIs/memory_files/memory.md', 'Memory and file system APIs', 'Memory']
- ['APIs/memory_files/file_system.md', 'Memory and file system APIs', 'File system']
- ['build_tools/options.md', 'Build tools', 'Build tool options']
- ['build_tools/studio.md', 'Build tools', 'mbed Studio']
- ['build_tools/ide.md', 'Build tools', 'mbed IDE']
- ['build_tools/cli.md', 'Build tools', 'mbed CLI']
- ['build_tools/offline.md', 'Build tools', 'Offline build tools']
- ['advanced/writing_apps.md', 'Advanced tutorials', 'Writing applications']
- ['advanced/versions.md', 'Advanced tutorials', 'Version control']
- ['advanced/debugging.md', 'Advanced tutorials', 'Debugging']
- ['advanced/DAP.md', 'Advanced tutorials', 'CMSIS-DAP and DAPLink']
- ['advanced/targets.md', 'Advanced tutorials', 'Targets']
- ['advanced/config_system.md', 'Advanced tutorials', 'Configuration system']
- ['advanced/writing_libs.md', 'Advanced tutorials', 'Writing libraries']
- ['porting/background.md', 'Porting to mbed OS 16.07', 'Porting overview']
- ['porting/porting_process.md', 'Porting to mbed OS 16.07', 'Porting process']
- ['porting/other_ports.md', 'Porting to mbed OS 16.07', 'Porting to other components']
