site_name: mbed OS Handbook

docs_dir: docs

pages:
- ['index.md','Introduction to mbed OS 5.0 and the handbook']
- ['getting_started/what_need.md', 'Getting started', 'What you need']
- ['getting_started/first_program.md', 'Getting started', 'First application']
- ['getting_started/serial_communication.md', 'Getting started', 'Connecting your device to a PC']
- ['getting_started/glossary.md', 'Getting started', 'Glossary']
- ['build_tools/options.md', 'Tools', 'Build tool options']
- ['build_tools/studio.md', 'Tools', 'mbed Studio']
- ['build_tools/online_comp.md', 'Tools', 'mbed Online Compiler']
- ['build_tools/cli.md', 'Tools', 'mbed CLI']
- ['build_tools/offline.md', 'Tools', 'Offline build tools']
- ['advanced/targets.md', 'Tools', 'Targets']
- ['advanced/config_system.md', 'Tools', 'Configuration system']
- ['advanced/debugging.md', 'Tools', 'Debugging']
- ['build_tools/collab_versions.md', 'Tools', 'Collaboration and version control']
- ['concepts/rtos.md', 'OS concepts', 'RTOS']
- ['concepts/thread_safety.md', 'OS concepts', 'Thread safety']
- ['concepts/memory.md', 'OS concepts', 'Memory models']
- ['concepts/bootstrap.md', 'OS concepts', 'Bootstrap sequence']
- ['APIs/intro.md', 'API overview', 'Writing applications with the mbed OS APIs']
- ['advanced/intro.md', 'Advanced tutorials', 'Introduction to the advanced tutorials']
- ['advanced/mbed_interface.md', 'Advanced tutorials', 'The mbed interface']
- ['advanced/writing_apps.md', 'Advanced tutorials', 'Writing applications']
- ['advanced/writing_libs.md', 'Advanced tutorials', 'Writing libraries']
- ['advanced/versions.md', 'Advanced tutorials', 'Version control']
- ['advanced/DAP.md', 'Advanced tutorials', 'CMSIS-DAP and DAPLink']
- ['porting/background.md', 'Adding hardware', 'Creating hardware and porting to mbed OS']
